#!/usr/bin/env bash
# build-reconner-ai.sh — pull the base, build Reconner's single Ollama model
# (wizard-ai — powers the animated Wizard's chat AND its Analyze Node/History/Tech
# actions), install the CWES knowledge base + the attack-type display summary
# alongside the Wizard's memory, smoke-test the model, and (optionally) point
# Reconner's settings file at it.
#
# Usage:
#   ./build-reconner-ai.sh                 # default flow
#   ./build-reconner-ai.sh --no-test       # skip the smoke-test prompt
#   ./build-reconner-ai.sh --no-settings   # don't touch ~/.reconner/settings.json
#   BASE=qwen2.5:14b ./build-reconner-ai.sh # smaller base for a tight box (9 GB)
#
# Re-running is safe — `ollama create` overwrites the tag in place.

set -euo pipefail

WIZARD_NAME="${WIZARD_NAME:-wizard-ai}"
# Default to the strongest local coder model (Qwen3-Coder 30B). It exceeds a
# 4 GB GPU, so most layers run on CPU/RAM — stronger answers, slower than a 7B.
# Override with BASE=… for a smaller model on constrained hardware.
BASE="${BASE:-qwen3-coder:30b}"
DEFAULT_BASE="qwen3-coder:30b"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WIZARD_MODELFILE="${WIZARD_MODELFILE:-$SCRIPT_DIR/Modelfile.wizard-ai}"
# Wizard memory + installed KB now live under ~/.reconner (same dir as settings).
WIZARD_MEMORY_DIR="$HOME/.reconner"
SETTINGS="$HOME/.reconner/settings.json"
# CWES knowledge base: the FULL base grounds wizard-ai; it is installed alongside
# the Wizard's memory so the model reads a stable copy. Reconner prunes
# lab/practical-exercise categories on load (theory only).
KB_SRC="${KB_SRC:-$HOME/Documents/Study/CWES/cwes_knowledge_base.json}"
KB_DST="$WIZARD_MEMORY_DIR/cwes_knowledge_base.json"
# Attack-type DISPLAY summary the Wizard popup's dropdown browser shows the user
# (generated by build-kb-attacks.py; the committed copy lives next to this script).
KB_SUMMARY_SRC="${KB_SUMMARY_SRC:-$SCRIPT_DIR/cwes_knowledge_base_summary.json}"
KB_SUMMARY_DST="$WIZARD_MEMORY_DIR/cwes_knowledge_base_summary.json"

DO_TEST=1
DO_SETTINGS=1
for arg in "$@"; do
    case "$arg" in
        --no-test)     DO_TEST=0 ;;
        --no-settings) DO_SETTINGS=0 ;;
        -h|--help)
            sed -n '2,14p' "$0"
            exit 0 ;;
        *) echo "unknown flag: $arg" >&2; exit 2 ;;
    esac
done

say() { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
ok()  { printf '\033[1;32m✓   %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m✗   %s\033[0m\n' "$*" >&2; exit 1; }

# build_model NAME MODELFILE — create the tag, rewriting its FROM line into a
# temp Modelfile when BASE was overridden (so the checked-in file is untouched).
build_model() {
    local name="$1" mf="$2" build_mf="$2"
    if [[ "$BASE" != "$DEFAULT_BASE" ]]; then
        build_mf="$(mktemp)"
        awk -v base="$BASE" '
            BEGIN { replaced = 0 }
            /^FROM[[:space:]]/ && !replaced { print "FROM " base; replaced = 1; next }
            { print }
        ' "$mf" > "$build_mf"
        say "Building $name from $mf (FROM $BASE)"
    else
        say "Building $name from $mf"
    fi
    ollama create "$name" -f "$build_mf"
    [[ "$build_mf" != "$mf" ]] && rm -f "$build_mf"
    ok "$name built"
}

# ─── 0. preconditions ────────────────────────────────────────────────────
command -v ollama >/dev/null 2>&1 \
    || die "ollama not installed. Try: curl -fsSL https://ollama.com/install.sh | sh"
ollama list >/dev/null 2>&1 \
    || die "ollama daemon not reachable. Start it with: sudo systemctl start ollama"
[[ -f "$WIZARD_MODELFILE" ]] \
    || die "Wizard Modelfile not found at: $WIZARD_MODELFILE"

# ─── 1. pull base ────────────────────────────────────────────────────────
say "Ensuring base model is present: $BASE"
if ollama list | awk '{print $1}' | grep -qx "$BASE"; then
    ok "base already pulled"
else
    ollama pull "$BASE"
    ok "base pulled"
fi

# ─── 2. build the model ──────────────────────────────────────────────────
build_model "$WIZARD_NAME" "$WIZARD_MODELFILE"

# Prepare the Wizard's persistent-memory folder (~/.reconner) so the assistant
# can store/recall conversations on first run. Migrate a legacy ~/.wizard-ai if
# one is still around (older installs kept memory + KB there).
if [[ -d "$HOME/.wizard-ai" && "$HOME/.wizard-ai" != "$WIZARD_MEMORY_DIR" ]]; then
    mkdir -p "$WIZARD_MEMORY_DIR"
    cp -an "$HOME/.wizard-ai/." "$WIZARD_MEMORY_DIR/" 2>/dev/null || true
    ok "migrated legacy ~/.wizard-ai → $WIZARD_MEMORY_DIR"
fi
mkdir -p "$WIZARD_MEMORY_DIR"
ok "memory folder ready: $WIZARD_MEMORY_DIR"

# Install the full CWES knowledge base (grounds wizard-ai).
if [[ -f "$KB_SRC" ]]; then
    cp -f "$KB_SRC" "$KB_DST"
    ok "knowledge base installed: $KB_DST"
else
    printf '\033[1;33m!   knowledge base source not found at %s\033[0m\n' "$KB_SRC"
    printf '\033[1;33m!   wizard-ai will run without CWES grounding until it exists\033[0m\n'
fi

# Install the attack-type display summary (drives the Wizard's dropdown browser).
# Regenerate it from build-kb-attacks.py if the committed copy is missing.
if [[ ! -f "$KB_SUMMARY_SRC" && -f "$SCRIPT_DIR/build-kb-attacks.py" ]]; then
    say "Generating attack-type knowledge base summary"
    python3 "$SCRIPT_DIR/build-kb-attacks.py" || true
fi
if [[ -f "$KB_SUMMARY_SRC" ]]; then
    cp -f "$KB_SUMMARY_SRC" "$KB_SUMMARY_DST"
    ok "knowledge-base summary installed: $KB_SUMMARY_DST"
else
    printf '\033[1;33m!   summary not found at %s\033[0m\n' "$KB_SUMMARY_SRC"
    printf '\033[1;33m!   run ./build-kb-attacks.py (the dropdown browser will be empty)\033[0m\n'
fi

# ─── 3. smoke test ───────────────────────────────────────────────────────
if (( DO_TEST )); then
    say "Smoke test: $WIZARD_NAME (Ctrl-C to skip)"
    ollama run "$WIZARD_NAME" "Greet me as a wizard, then in one line tell me what to check on a login form served over http."
    ok "$WIZARD_NAME smoke test returned"
fi

# ─── 4. wire Reconner ────────────────────────────────────────────────────
if (( DO_SETTINGS )); then
    say "Pointing Reconner at $WIZARD_NAME (settings: $SETTINGS)"
    mkdir -p "$(dirname "$SETTINGS")"
    python3 - "$SETTINGS" "$WIZARD_NAME" <<'PY'
import json, sys, pathlib
path = pathlib.Path(sys.argv[1])
wizard = sys.argv[2]
data = {}
if path.exists():
    try:
        data = json.loads(path.read_text())
    except Exception:
        data = {}
data['wizard_model'] = wizard
data.pop('model', None)   # legacy reconner-ai key — removed
path.write_text(json.dumps(data, indent=2) + '\n')
print(f'wrote wizard_model={wizard!r} to {path}')
PY
    ok "settings updated — Reconner will use $WIZARD_NAME on the next AI call"
fi

say "Done."
